language: java

git:
  depth: false

jdk:
  - openjdk8
  - openjdk11

env:
  - TEST_MILL_VERSION=
  - TEST_MILL_VERSION=0.5.7
  - TEST_MILL_VERSION=0.5.8
  - TEST_MILL_VERSION=0.5.9

script:
  - ./millw -i version
  - ./millw -i test
